engines:
  csslint:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR1,PSR2"
  phpmd:
    enabled: true
    config:
      rulesets: "codesize,design,unusedcode"
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.jsx"
  - "**.php"
  - "**.module"
  - "**.inc"
exclude_paths:
  - "common/css/FontAwesome/**"
  - "common/css/Themes/**"
  - "common/php/vendor/**"
  - "common/js/vendor/**"
